TEAM_NAME = [
    ("애틀랜타", "Atlanta Hawks"),
    ("보스턴", "Boston Celtics"),
    ("브루클린", "Brooklyn Nets"),
    ("샬럿", "Charlotte Hornets"),
    ("시카고", "Chicago Bulls"),
    ("클리블랜드", "Cleveland Cavaliers"),
    ("댈러스", "Dallas Mavericks"),
    ("덴버", "Denver Nuggets"),
    ("디트로이트", "Detroit Pistons"),
    ("골든스테이트", "Golden State Warriors"),
    ("휴스턴", "Houston Rockets"),
    ("인디애나", "Indiana Pacers"),
    ("LA 클리퍼스", "LA Clippers"),
    ("LA 레이커스", "Los Angeles Lakers"),
    ("멤피스", "Memphis Grizzlies"),
    ("마이애미", "Miami Heat"),
    ("밀워키", "Milwaukee Bucks"),
    ("미네소타", "Minnesota Timberwolves"),
    ("뉴올리언스", "New Orleans Pelicans"),
    ("뉴욕", "New York Knicks"),
    ("오클라호마시티", "Oklahoma City Thunder"),
    ("올랜도", "Orlando Magic"),
    ("필라델피아", "Philadelphia 76ers"),
    ("피닉스", "Phoenix Suns"),
    ("포틀랜드", "Portland Trail Blazers"),
    ("새크라멘토", "Sacramento Kings"),
    ("샌안토니오", "San Antonio Spurs"),
    ("토론토", "Toronto Raptors"),
    ("유타", "Utah Jazz"),
    ("워싱턴", "Washington Wizards")
]
